const REACT_APP_PAGINATION_COUNT = 10;
const REACT_APP_API_ENDPOINT = "https://www.vrbo.com/serp/g";
const REACT_APP_MAX_FILTER_COUNT = 5;
const REACT_APP_MIN_FILTER_COUNT = 0;

const REACT_APP_MAPBOX_TOKEN =
  "pk.eyJ1Ijoic2FyYXRoLXByYXZhbGxpa2EiLCJhIjoiY2wzM3o1YzJyMHoxMTNpcDlnMjN6eTF3aCJ9.cvOqxZ-AWuk2KYc7-hgUuQ";
const REACT_APP_MAPBOX_STYLE = "mapbox://styles/mapbox/dark-v8";

export {
  REACT_APP_PAGINATION_COUNT,
  REACT_APP_API_ENDPOINT,
  REACT_APP_MAX_FILTER_COUNT,
  REACT_APP_MIN_FILTER_COUNT,
  REACT_APP_MAPBOX_TOKEN,
  REACT_APP_MAPBOX_STYLE,
};
